import type { ComponentProps } from "react";

import { defineComponentDesign } from "../../shared/component-design";
import { DocumentWorkspacePanels as ComponentUnderDesign } from "./DocumentWorkspacePanels";

export default defineComponentDesign(ComponentUnderDesign, {
  isStateful: false,
  defaults: {
    projectId: "",
    projectLabel: "",
    documentId: "",
    documentLabel: "",
    documentSource: "",
    documentSourceLabel: "",
    documentKind: "component",
    mode: "app",
    mobilePane: "tree",
    sidebarView: "tree",
    browserView: "files",
    modeDocumentAvailable: false,
    hasRoot: false,
    rootPicker: false,
    canCreate: false,
    entries: [],
    files: [],
    catalog: [],
    rows: [],
    showInternals: false,
    insertMode: false,
    strictUiViolations: [],
    canvasRootId: "",
    canvasSelectedId: "",
    canvasSelectionLabel: "",
    canvasSlots: [],
    pickerLabel: "",
    pickerEntries: [],
    onBrowserViewChange: () => undefined,
    onSidebarViewChange: () => undefined,
    onModeChange: () => undefined,
    onDocumentSelect: () => undefined,
    onFileOpened: () => undefined,
    onCatalogSelect: () => undefined,
    onCreate: () => undefined,
    onOpenRootPicker: () => undefined,
    onSelect: () => undefined,
    onCanvasDeselect: () => undefined,
    onHover: () => undefined,
    onHoverInternals: () => undefined,
    onNavigate: () => undefined,
    onCollapseAll: () => undefined,
    onToggleInsert: () => undefined,
    onToggleInternals: () => undefined,
    onOpenSlot: () => undefined,
    onClearSlot: () => undefined,
    onRemoveOutlet: () => undefined,
    onClosePicker: () => undefined,
    onInsertComponent: () => undefined,
    onContextMenu: () => undefined,
    onEditComponent: () => undefined,
    onDomSnapshot: () => undefined,
    onMobileDrawerClose: () => undefined,
  } as unknown as ComponentProps<typeof ComponentUnderDesign>,
  designs: { default: {} },
  render: (props: ComponentProps<typeof ComponentUnderDesign>) => <ComponentUnderDesign {...props} />,
});
